### ISSUE TITLE
Error when downloading gene expression files

### ISSUE THREAD

**Issue by malonzm1** [MaayanLab/archs4#29]
Hi,

When I download certain gene expression files (e.g. GSE121380) from the generated R scripts I run into the following error: 

Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  :
  Not enough memory to read data! Try to read a subset of data by specifying the index or count parameter.
Calls: t ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Error: Error in h5checktype(). H5Identifier not valid.
Execution halted

I've tried using up to 120gb and I still get the same error.

Pls. advise. Thanks.

**Comment by lachmann12** [comment]
If it is happening for GSE121380, which has 13 samples memory should of course not be the problem. The problem here is that the samples are very large single cell studies with 300+ million reads. ARCHS4 is currently not optimized to align single cell data and has most likely failed to align these samples in the updated pipeline. They are not in the newest ARCHS4 data release. We hope to be able to support them again in the future. 

To check the variable sample_locations should not be empty.
