### ISSUE TITLE
CPM and TPM from gene_abundance.tsv

### ISSUE THREAD

**Issue by malonzm1** [MaayanLab/archs4#36]
Hi,

In issue https://github.com/MaayanLab/archs4/issues/30, you shared how to obtain gene abundance values from the transcript expression levels. I would like to know how to obtain CPM and TPM values from these gene abundance values (gene_abundance.tsv). From what I understand some normalization is already performed to obtain gene_abundance.tsv. Can I still just perform the regular calculations for CPM and TPM?

Thanks.

**Comment by lachmann12** [comment]
This code repository is somewhat out of date. You can check out the python package that can be used to work with archs4 data. The package also allows the local execution of the archs4 pipeline. On the download page of ARCHS4 we also support the TPM data at transcript level. CPM can be applied to the gene level data if you want. TPM on gene level is a bit weird since it requires the length of the gene, but since a gene has usually multiple transcripts with different length that is ill defined. https://github.com/MaayanLab/archs4py
