### ISSUE TITLE
Duplicate gene symbols

### ISSUE THREAD

**Issue by yotamroshuji** [MaayanLab/archs4#38]
Hi, 
I've noticed that there are some genes that have the same symbol, however have a different index (meaning they might have different sample values).
<img width="466" alt="image" src="https://github.com/MaayanLab/archs4/assets/96071821/b383863e-9b50-48a4-bf0d-2c380716af48">

It looks like there are around ~2000 duplicate gene symbols, with some appearing over 10 times:
<img width="462" alt="image" src="https://github.com/MaayanLab/archs4/assets/96071821/5978a28c-6902-49f4-93af-c72cac16190a">

Any idea what could cause this?

**Comment by lachmann12** [comment]
Hi, 

it has something to do with the Ensembl annotations that seem to have duplicate Ensembl id mappings to the same gene. As far as I know the values for both entries are identical so you can just drop the duplicates without loosing any information.

Best,
Alex

**Comment by amnahsiddiqa** [comment]
hi @lachmann12. I really appreciate this resource , it is truly great help. But  apparently I noticed this too and as you may see in the screenshot attached that values of each entry is not identical, should I imply int was at transcript level rather than gene ?
![Screenshot 2024-06-07 at 1 13 02 PM](https://github.com/MaayanLab/archs4/assets/28387956/944a3206-eab0-43f8-9695-367141fb172b)
